# Generated by Django 4.1.7 on 2023-06-09 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_remove_customerprofile_address_staffprofile_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StaffProfile',
        ),
    ]
