# Generated by Django 4.1.7 on 2023-07-14 07:58

import customer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_address_created_address_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, validators=[customer.models.valid_phone_number]),
        ),
    ]
