# Generated by Django 4.1.7 on 2023-07-14 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_review_product'),
        ('cart', '0003_remove_cart_subtotal_alter_cart_customer'),
        ('customer', '0005_alter_customerprofile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='products',
            field=models.ManyToManyField(through='cart.Cart', to='catalog.product'),
        ),
    ]
