# Generated by Django 4.1.7 on 2023-08-22 18:47

import customer.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_address_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, validators=[customer.validators.valid_date]),
        ),
    ]
