# Generated by Django 4.1.7 on 2023-06-10 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_category_description_category_supercategory_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='supercategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='catalog.category'),
        ),
    ]
