# Generated by Django 4.1.7 on 2023-06-26 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0004_address_created_address_last_updated"),
        ("catalog", "0008_alter_review_product"),
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="products",
        ),
        migrations.RemoveField(
            model_name="cart",
            name="total",
        ),
        migrations.AddField(
            model_name="cart",
            name="number",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="cart",
            name="product",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="catalog.product",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cart",
            name="subtotal",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="cart",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart",
                to="customer.customerprofile",
            ),
        ),
        migrations.DeleteModel(
            name="CartProduct",
        ),
    ]
