# Generated by Django 4.1.7 on 2023-07-14 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_customerprofile_phone_number'),
        ('cart', '0002_remove_cart_products_remove_cart_total_cart_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='subtotal',
        ),
        migrations.AlterField(
            model_name='cart',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customerprofile'),
        ),
    ]
