# Generated by Django 4.1.7 on 2023-08-22 19:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_delivery_delivery_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='subtotal',
        ),
        migrations.AlterField(
            model_name='delivery',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2023, 8, 24, 19, 40, 2, 33192)),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=1.99, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='estimated_arrival_date',
            field=models.DateField(default=datetime.datetime(2023, 8, 27, 19, 40, 2, 33161)),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
