# Generated by Django 4.1.7 on 2023-08-24 17:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_delivery_delivery_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2023, 8, 26, 17, 32, 51, 160807)),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='estimated_arrival_date',
            field=models.DateField(default=datetime.datetime(2023, 8, 29, 17, 32, 51, 160771)),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.order')),
            ],
        ),
    ]
