# Generated by Django 4.1.7 on 2023-08-24 20:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_delivery_delivery_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2023, 8, 26, 20, 29, 33, 35320)),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='estimated_arrival_date',
            field=models.DateField(default=datetime.datetime(2023, 8, 29, 20, 29, 33, 35288)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
    ]
