# Generated by Django 4.1.7 on 2023-08-30 18:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_delivery_delivery_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'verbose_name_plural': 'deliveries'},
        ),
        migrations.AlterField(
            model_name='delivery',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2023, 9, 1, 18, 18, 23, 724760)),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='estimated_arrival_date',
            field=models.DateField(default=datetime.datetime(2023, 9, 4, 18, 18, 23, 724747)),
        ),
    ]
